version: "3"

services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3305:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 500M
    depends_on:
      - mysql
    ports:
      - "1111:80"
  php:
    image: wodby/php:7.4
    container_name: "${APP_NAME}_php"
    environment:
      DB_HOST: mysql
      DB_USER: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_DATABASE
      DB_DRIVER: $DB_DRIVER
      PHP_MEMORY_LIMIT: 10240M
    depends_on:
      - mysql
    volumes:
      - ./src/:/var/www/html
  nginx:
    image: wodby/nginx:1.21
    container_name: "${APP_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/public
      NGINX_VHOST_PRESET: php
    volumes:
      - ./src/:/var/www/html
    labels:
      - 'traefik.backend=${APP_NAME}_nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${APP_URL}'
    ports:
      - '89:80'
